### ISSUE TITLE
# User Story IV - Create New Task

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#126]
# User Story IV
As a **user** I can **create a new task** by **following an intuitive interface**.
- [x] #193 
- [x] #194 
_Originally posted by @mnichols08 in https://github.com/chingu-voyages/v47-tier1-team-04/discussions/29#discussioncomment-8102915_

**Comment by Stacy-Riley** [comment]
I took some time to think about what would be needed to complete these items and listed them below:

1. User can press "Trashcan" icon and the task disappears from its category. 
2. Task is moved to a completed array that is displayed in something onscreen as a "Complete Folder" (we don't have a design for this.
3. User can open the completed folder and another page or modal opens up.
4. The tasks are listed and in the "checked" format, the same format as displayed in the initial app view.
5. If the user un-selects a task, it will disappear and return to its category.
6. There will be a "Delete All" button at the top of this "Complete Folder".
7. User presses "Delete All" button and a message modal displays.
8. Message appears stating "This will be a permanent delete of your completed tasks.  Would you like to continue?"
9. There will need to be two buttons: "Yes, delete all" and "No, cancel".
10. "No, cancel" closes the modal message popup and leaves the user still inside of the "Complete Folder".
11. "Yes, delete all" removes all tasks from the "Complete" array and nothing will be displayed. User will still be inside of the "Completed Folder" or we can send them back to the app.
12. Either way, the "Completed Folder" will need an (X) to close it and return user to app.
