### ISSUE TITLE
# User Story XIII - Save Progress

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#127]
# User Story XIII
As a **user** I can **press a button to save my work** and then **close the browser and still come back to the same data.**
  - [x] #186
  - [x] #205 
_Originally posted by @mnichols08 in https://github.com/chingu-voyages/v47-tier1-team-04/discussions/29#discussioncomment-8103305_

**Comment by mnichols08** [comment]
We discussed Auto Saving at the meeting and agreed it would be a great implementation if possible. 

I think the ability to opt-out of this would also be crucial.

**Comment by egpennington** [comment]
use local storage would be one task.  that way the info is current and saved
