### ISSUE TITLE
# User Story XIV - Review Completed Task

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#129]
# User Story XIV
As a **user** I can **review a completed task** by **clicking on it.** Doing so will **change it's status to incomplete.**
- [x] #155
- [x] #188

_Originally posted by @mnichols08 in https://github.com/chingu-voyages/v47-tier1-team-04/discussions/29#discussioncomment-8103332_

**Comment by egpennington** [comment]
i like the two buttons for delete and edit.  along with the ellipse checkoff, i believe that covers this user story.  clicking on the check box/ellipse again, takes off the check, thereby resetting it.
