### ISSUE TITLE
# User Story V - Remove Task

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#130]
# User Story V
As a **user** I can **remove a task** so that **the interface does not get over encumbered.**
  - [x] #195
  - [x] #196
  - [x] #197
_Originally posted by @mnichols08 in https://github.com/chingu-voyages/v47-tier1-team-04/discussions/29#discussioncomment-8102946_

**Comment by Stacy-Riley** [comment]
I'll start working on this.

**Comment by Stacy-Riley** [comment]
I took some time to think about what would be needed to complete these items and listed them below:

1. User can press "Trashcan" icon and the task disappears from its category.
2. Task is moved to a completed array and stored for bonus item below.

**I suggest we save this for a bonus item:**
1. "Complete Folder" (we don't have a design for this.) This will house all the items the user deleted.
2. User can open the completed folder and another page or modal opens up.
3. The tasks are listed and in the "checked" format, the same format as displayed in the initial app view.
4. If the user un-selects a task, it will disappear and return to its category.
5. There will be a "Delete All" button at the top of this "Complete Folder".
6. User presses "Delete All" button and a message modal displays.
7. Message appears stating "This will be a permanent delete of your completed tasks. Would you like to continue?"
8. There will need to be two buttons: "Yes, delete all" and "No, cancel".
9. "No, cancel" closes the modal message popup and leaves the user still inside of the "Complete Folder".
10. "Yes, delete all" removes all tasks from the "Complete" array and nothing will be displayed. User will still be inside of the "Completed Folder" or we can send them back to the app.
11. Either way, the "Completed Folder" will need an (X) to close it and return user to app.

**Comment by Stacy-Riley** [comment]
I am trying to push a secondary branch here but it continues to reject in my terminal.
