### ISSUE TITLE
Structure the data on screen so it can be manipulated later

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#133]
- [x] Ensure that #116 is complete

Think about how to put the data on screen with foresight to how you might manipulate the data on screen later. You might want to place segments that you want to be able to change later with ease inside of spans with specific IDs, or come up with a delimiter such as using `{{` `}}` curly braces around segments you will want to later change.

- [ ] Implement a method of accessing/manipulating key areas within the html document

**Comment by mnichols08** [comment]
You could place your data segments within curly braces perhaps `{{` `}}` or maybe place a span around them and assign an ID, but it will be wise to do this earlier than later.

**Comment by jayanti-neu** [comment]
I think using span with id on the values that will be changed by the user will work since we can directly access the value by the id. Maybe when using the delimiter we might have to search for it ?

**Comment by mnichols08** [comment]
I agree. Where are we at in regards to completing this task?
