### ISSUE TITLE
Initialize functionality for the user to sort tasks

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#208]

**Comment by n-keerthi-gayathri** [comment]
@mnichols08 please assign me this issue

**Comment by mnichols08** [comment]
@n-keerthi-gayathri two things… one we aren’t quite to this stage so the task would not be possible just yet. Two, we are participating in a Chingu Voyage. I’m not sure if we are allowed to accept code from an outside source or not. @jdmedlock  would have to weigh in on it to be honest. I’m flattered that you have found our repository and I’d be happy to accept contributions personally.
