### ISSUE TITLE
Create Folder Structure

### ISSUE THREAD

**Issue by egpennington** [chingu-voyages/v47-tier1-team-04#37]
**__Task Description__**
# Folder Structure
1. Check out this branch locally. `git checkout 37/development/folder-structure`
1. Create a new branch to make proposed changes to. `git switch -c <issue-number>/<type-of-change>/<description-of-change>/<github-username>`
1. Create two folders in the root directory.
- The first is the primary folder for our uncompiled documents. We will pretty much only be editing files within this folder from here on out.
1.  Call the folder something like `src` or `dev` or whatever makes sense for our uncompiled files to be stored. Place blank html, css, js files in here. 

1.  Next create another folder to house the built website.
- Call this folder something like `dist`, `public`, `build`, etc. to represent the compiled documents of a project. This folder is ignored by git already because it is typically bloat and not necessary to be tracked.

**__Technical Considerations__**
This makes our project easier to browse through because it will allow us to organize our files in a logical way. It is also considered a best practice and certainly will be found "in the wild".

**Comment by mnichols08** [comment]
I think a great idea would be to initialize our development server with a service like [webpack](https://webpack.js.org/). But the choice is yours as the developer how to proceed from here. The requirement is that the application has an html file, css file, and a js file, inside of a folder named to describe the working files of a project. (Very commonly src or similar).
