### ISSUE TITLE
# User Story XI - Initial Read

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#63]
**__User Story Description__**
As a **user** when first load the web application, I can see that there is already **data populated within the calendar for me** so that I can **visualize the intended outcome.**
- [x] #153
- [x] #154
- [x] #185 

**__Additional Considerations__**
We were provided with a JSON dataset file found within the assets folder.

Refer to #186 comments for a good idea on doing these tasks

**Comment by egpennington** [comment]
a task would be to have javascript function load the data on open of the app.  auto populate with the json file along with the user's local storage.  therefore, another task would be to have the user able to add tasks and description.  so that would be a task to tackle.

**Comment by mnichols08** [comment]
> a task would be to have javascript function load the data on open of the app. auto [and] populate with the json file along with the user's local storage.

**Comment by mnichols08** [comment]
> another task would be to have the user able to add tasks and description. so that would be a task to tackle.
