### ISSUE TITLE
# EPIC II - Data Initialization

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#66]
**__Feature Description__**
Up until now this application is just a static representation of the data that we have been given. In this EPIC we are going to begin to add functionality.

**__Major User Stories/tasks__**
- [x] Ensure that #59 is complete.
- [x] #63 
  As a **user**, when first loading the web application, I can see that there is already **data populated within the calendar for me** so that I can **visualize the intended outcome.**
  - [x] #153
  - [x] #154
  - [x] #185 
- [x] #129
  As a **user** I can **review a completed task** by **clicking on it.** Doing so will **change it's status to incomplete.**
  - [x] #155
  - [x] #188 
- [x] #128 
  As a **user** I can **click on an incomplete task** to **view detailed information about it in a popup.**
  - [x] #167
  - [x] #168
  - [x] #169
  - [x] #170
- [x] #127
  As a **user** I can **press a button to save my work** and then **close the browser and still come back to the same data.**
  - [x] #186
  - [x] #205

**__Additional Considerations__**
We were provided with a JSON dataset file found within the assets folder.

**Comment by mnichols08** [comment]
As of right now, there are User Stories associated with this EPIC.

Tasks will be made after I meet with some developers to get a sense of which direction we are going to code this, but these won't even begin until the next sprint anyway so please do not stress.

**Comment by Stacy-Riley** [comment]
For this branch, it looks like we can check off "Obtain the preset data somehow"

**Comment by mnichols08** [comment]
> For this branch, it looks like we can check off "Obtain the preset data somehow"

Agreed I have done that and I opened a PR to merge it into alpha as well.

I heavily modified the code I worked on with you guys yesterday.

I published it to branch `153/feat/more-advanced-but-better/mn/`
